@startuml 盛岡商事
left to right direction
actor 担当者A#DDDDDD;line:black;line.bold;
rectangle 新規販売管理システム {
usecase 注文商品をシステムで確認する << U1 >>
usecase 商品の出荷状況をシステムに登録する << U2 >>
}
担当者A --> 注文商品をシステムで確認する
担当者A -->商品の出荷状況をシステムに登録する
@endum